source("functions.R")

########################################
### MISCELLANEOUS LABELS AND FACTORS ###
########################################

### Selection of ALL strategies and screening types
all_strats_3ltcfs = c("adm", "sym", "adm_sym", 
                      "d01", "d02", "d03", "d04", "d05", "d06", "d07", "d08", "d09",
                      "adm_sym_d01", "adm_sym_d02", "adm_sym_d03", "adm_sym_d04", "adm_sym_d05",
                      "adm_sym_d06", "adm_sym_d07", "adm_sym_d08", "adm_sym_d09",
                      "adm_sym_d01_d02", "adm_sym_d01_d03", "adm_sym_d01_d04", "adm_sym_d01_d05", 
                      "adm_sym_d01_d06", "adm_sym_d01_d07", "adm_sym_d01_d08", "adm_sym_d01_d09")
all_strats_3ltcfs_labels = c("Admissions (routine PCR)", "Symptoms (routine PCR)",'Baseline (routine PCR)', 
                             paste0('Only Ag-RDT (day ',1:9, ')'),
                             paste0('Ag-RDT (day ', 1:9, ')'),
                             paste0('Ag-RDT (days 1 & ',2:9,')'))

selected_targets = c('All', 'Patients', 'Staff', 'None')
selected_targets_labels = c('patients & staff', 'patients', 'staff', 'no screening')

selected_measures = c("quantile", "single mean", "distribution of means", "total", "bootstrap")

vec_3ltcfs_labels = c('LTCF 1 (high risk)', 'LTCF 2 (moderate risk)', 'LTCF 3 (low risk)')


lot = "lot3"
v_LTCF_x = 1:3
v_sens_function_x = c('time-varying','uniform', 'perfect')
files_CTC = 5 # out of 100 (limited to 5 here because only surveillance data provided only for first 5 CTC simulations due to space); all 100 can be generated by running surveillance loop
filepath_lot = "Output_lot3/"

testing_rounds_x = 100
vec_screening_types = c("PCR", "RDT1", "RDT2")
vec_screening_targets = c("Patients", "Staff", "All")
vec_surveillance_strategies = c(
  "adm","sym","adm_sym",
  "d01","d02","d03","d04","d05","d06","d07","d08", "d09",
  "adm_sym_d01","adm_sym_d02","adm_sym_d03","adm_sym_d04","adm_sym_d05","adm_sym_d06","adm_sym_d07","adm_sym_d08","adm_sym_d09",
  "adm_sym_d01_d02","adm_sym_d01_d03","adm_sym_d01_d04","adm_sym_d01_d05","adm_sym_d01_d06","adm_sym_d01_d07","adm_sym_d01_d08","adm_sym_d01_d09"
)


filepath_output_prepared_lot3 = paste0(getwd(), "/Surveillance/Output/Output_prepared_lot3/")
filepath_outcomes_lot3 = paste0(getwd(), "/Surveillance/Output/Outcomes_lot3/")

###################################
### PREPARE SURVEILLANCE OUTPUT ###
###################################


# dataSurveillanceOutput0202_1_1_timevarying = f_prepare_surveillance_output(lot, files_CTC, testing_rounds_x, "0.20.2", 1, 1, vec_surveillance_strategies, vec_screening_types, vec_screening_targets, "time-varying")
# dataSurveillanceOutput0202_1_1_uniform = f_prepare_surveillance_output(lot, files_CTC, testing_rounds_x, "0.20.2", 1, 1, vec_surveillance_strategies, vec_screening_types, vec_screening_targets, "uniform")
# dataSurveillanceOutput0202_1_1_perfect = f_prepare_surveillance_output(lot, files_CTC, testing_rounds_x, "0.20.2", 1, 1, vec_surveillance_strategies, vec_screening_types, vec_screening_targets, "perfect")
# dataSurveillanceOutput0202_1_1 = rbind(dataSurveillanceOutput0202_1_1_timevarying, dataSurveillanceOutput0202_1_1_uniform, dataSurveillanceOutput0202_1_1_perfect)
# 
# dataSurveillanceOutput0202_2_1_timevarying = f_prepare_surveillance_output(lot, files_CTC, testing_rounds_x, "0.20.2", 2, 1, vec_surveillance_strategies, vec_screening_types, vec_screening_targets, "time-varying")
# dataSurveillanceOutput0202_2_1_uniform = f_prepare_surveillance_output(lot, files_CTC, testing_rounds_x, "0.20.2", 2, 1, vec_surveillance_strategies, vec_screening_types, vec_screening_targets, "uniform")
# dataSurveillanceOutput0202_2_1_perfect = f_prepare_surveillance_output(lot, files_CTC, testing_rounds_x, "0.20.2", 2, 1, vec_surveillance_strategies, vec_screening_types, vec_screening_targets, "perfect")
# dataSurveillanceOutput0202_2_1 = rbind(dataSurveillanceOutput0202_2_1_timevarying, dataSurveillanceOutput0202_2_1_uniform, dataSurveillanceOutput0202_2_1_perfect)
# 
# dataSurveillanceOutput0505_2_2_timevarying = f_prepare_surveillance_output(lot, files_CTC, testing_rounds_x, "0.50.5", 2, 2, vec_surveillance_strategies, vec_screening_types, vec_screening_targets, "time-varying")
# dataSurveillanceOutput0505_2_2_uniform = f_prepare_surveillance_output(lot, files_CTC, testing_rounds_x, "0.50.5", 2, 2, vec_surveillance_strategies, vec_screening_types, vec_screening_targets, "uniform")
# dataSurveillanceOutput0505_2_2_perfect = f_prepare_surveillance_output(lot, files_CTC, testing_rounds_x, "0.50.5", 2, 2, vec_surveillance_strategies, vec_screening_types, vec_screening_targets, "perfect")
# dataSurveillanceOutput0505_2_2 = rbind(dataSurveillanceOutput0505_2_2_timevarying, dataSurveillanceOutput0505_2_2_uniform, dataSurveillanceOutput0505_2_2_perfect)
# 
# ### Save prepared surveillance output data
# save(dataSurveillanceOutput0202_1_1, file = paste0(filepath_output_prepared_lot3, "m_surveillance_prepared_0202_1_1.Rdata"))
# save(dataSurveillanceOutput0202_2_1, file = paste0(filepath_output_prepared_lot3, "m_surveillance_prepared_0202_2_1.Rdata"))
# save(dataSurveillanceOutput0505_2_2, file = paste0(filepath_output_prepared_lot3, "m_surveillance_prepared_0505_2_2.Rdata"))


### Load prepared surveillance output data
# load(paste0(filepath_output_prepared_lot3, "m_surveillance_prepared_0202_1_1.Rdata"))
# load(paste0(filepath_output_prepared_lot3, "m_surveillance_prepared_0202_2_1.Rdata"))
# load(paste0(filepath_output_prepared_lot3, "m_surveillance_prepared_0505_2_2.Rdata"))


#######################################
### SUMMARIZE SURVEILLANCE OUTCOMES ###
#######################################

############################################
### INCIDENCE W and W/O BASELINE TESTING ###
############################################

### Prepare data ###
dataIncidenceBeforeAfterBaseline0202_1_1 = dataSurveillanceOutput0202_1_1%>%
  filter(stratSurveillance == 'adm_sym', typeDailyScreening == 'PCR', targetDailyScreening == 'All', sensitivity_function == "time-varying")%>%
  mutate(incNosocomial_afterTesting = incNosocomial - infAverted)%>%
  dplyr::select(c(simulationCTC, testingRound, incNosocomial, incNosocomial_afterTesting))%>%
  pivot_longer(-c(simulationCTC, testingRound), names_to = 'Testing', values_to = 'Incidence')%>%
  mutate(Testing = ifelse(Testing == 'incNosocomial', 'No testing', 'Baseline PCR testing'))%>%
  mutate(LTCF = vec_3ltcfs_labels[1])

dataIncidenceBeforeAfterBaseline0202_2_1 = dataSurveillanceOutput0202_2_1%>%
  filter(stratSurveillance == 'adm_sym', typeDailyScreening == 'PCR', targetDailyScreening == 'All', sensitivity_function == "time-varying")%>%
  mutate(incNosocomial_afterTesting = incNosocomial - infAverted)%>%
  dplyr::select(c(simulationCTC, testingRound, incNosocomial, incNosocomial_afterTesting))%>%
  pivot_longer(-c(simulationCTC, testingRound), names_to = 'Testing', values_to = 'Incidence')%>%
  mutate(Testing = ifelse(Testing == 'incNosocomial', 'No testing', 'Baseline PCR testing'))%>%
  mutate(LTCF = vec_3ltcfs_labels[2])

dataIncidenceBeforeAfterBaseline0505_2_2 = dataSurveillanceOutput0505_2_2%>%
  filter(stratSurveillance == 'adm_sym', typeDailyScreening == 'PCR', targetDailyScreening == 'All', sensitivity_function == "time-varying")%>%
  mutate(incNosocomial_afterTesting = incNosocomial - infAverted)%>%
  dplyr::select(c(simulationCTC, testingRound, incNosocomial, incNosocomial_afterTesting))%>%
  pivot_longer(-c(simulationCTC, testingRound), names_to = 'Testing', values_to = 'Incidence')%>%
  mutate(Testing = ifelse(Testing == 'incNosocomial', 'No testing', 'Baseline PCR testing'))%>%
  mutate(LTCF = vec_3ltcfs_labels[3])

dataIncidenceBeforeAfterBaseline = rbind(dataIncidenceBeforeAfterBaseline0202_1_1, dataIncidenceBeforeAfterBaseline0202_2_1, dataIncidenceBeforeAfterBaseline0505_2_2)
dataIncidenceBeforeAfterBaseline_Means = dataIncidenceBeforeAfterBaseline%>%group_by(LTCF, Testing)%>%summarise(Incidence_mean = mean(Incidence))
dataIncidenceBeforeAfterBaseline_Medians = dataIncidenceBeforeAfterBaseline%>%group_by(LTCF, Testing)%>%summarise(Incidence_median = median(Incidence))

# save(dataIncidenceBeforeAfterBaseline, file = paste0(filepath_outcomes_lot3, "dataIncidenceBeforeAfterBaseline.Rdata"))
# save(dataIncidenceBeforeAfterBaseline_Means, file = paste0(filepath_outcomes_lot3, "dataIncidenceBeforeAfterBaseline_Means.Rdata"))
# save(dataIncidenceBeforeAfterBaseline_Medians, file = paste0(filepath_outcomes_lot3, "dataIncidenceBeforeAfterBaseline_Medians.Rdata"))


#############################
### INF AVERTED: ABSOLUTE ###
#############################

dataInfAverted0202_1_1 = f_infAverted(dataSurveillanceOutput0202_1_1)
dataInfAverted0202_2_1 = f_infAverted(dataSurveillanceOutput0202_2_1)
dataInfAverted0505_2_2 = f_infAverted(dataSurveillanceOutput0505_2_2)

# 3 LTCFs, selected timings
dataInfAverted_3ltcfs = rbind(dataInfAverted0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                              dataInfAverted0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                              dataInfAverted0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataInfAverted_3ltcfs$stratSurveillance = factor(dataInfAverted_3ltcfs$stratSurveillance, levels = rev(all_strats_3ltcfs), labels = rev(all_strats_3ltcfs_labels))
dataInfAverted_3ltcfs$targetDailyScreening = factor(dataInfAverted_3ltcfs$targetDailyScreening, levels = rev(selected_targets), labels = rev(selected_targets_labels))

# prep data for plotting:
dataInfAverted_3ltcfs_compareCIs = dataInfAverted_3ltcfs%>%
  mutate(infAverted_quantiles_mean = infAverted_500,infAverted_quantiles_lower = infAverted_250, infAverted_quantiles_upper = infAverted_750)%>%
  dplyr::select(-c(infAverted_025, infAverted_250, infAverted_500, infAverted_750, infAverted_975, infAverted_total_SD,
                   infAverted_singlemean_SD, infAverted_distrmean_SEM, immunity, networkIPC))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central",
    ))%>%
  dplyr::select(-name)%>%
  pivot_wider(values_from = value, names_from = location)

dataInfAverted_3ltcfs_compareCIs$methodCI = factor(dataInfAverted_3ltcfs_compareCIs$methodCI, levels = selected_measures)

# save(dataInfAverted_3ltcfs_compareCIs, file = paste0(filepath_outcomes_lot3, "dataInfAverted_3ltcfs_compareCIs.Rdata"))


#############################
### INF AVERTED: RELATIVE ###
#############################

dataInfAvertedRelative0202_1_1 = f_infAverted_relative(dataSurveillanceOutput0202_1_1)
dataInfAvertedRelative0202_2_1 = f_infAverted_relative(dataSurveillanceOutput0202_2_1)
dataInfAvertedRelative0505_2_2 = f_infAverted_relative(dataSurveillanceOutput0505_2_2)


# 3 LTCFs, selected timings
dataInfAvertedRelative_3ltcfs = rbind(dataInfAvertedRelative0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                              dataInfAvertedRelative0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                              dataInfAvertedRelative0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataInfAvertedRelative_3ltcfs$stratSurveillance = factor(dataInfAvertedRelative_3ltcfs$stratSurveillance, levels = rev(all_strats_3ltcfs), labels = rev(all_strats_3ltcfs_labels))
dataInfAvertedRelative_3ltcfs$targetDailyScreening = factor(dataInfAvertedRelative_3ltcfs$targetDailyScreening, levels = rev(selected_targets), labels = rev(selected_targets_labels))


# prep data for plotting:
dataInfAvertedRelative_3ltcfs_compareCIs = dataInfAvertedRelative_3ltcfs%>%
  mutate(infAvertedRelative_quantiles_mean = infAvertedRelative_500,infAvertedRelative_quantiles_lower = infAvertedRelative_250, infAvertedRelative_quantiles_upper = infAvertedRelative_750)%>%
  dplyr::select(-c(infAvertedRelative_025, infAvertedRelative_250, infAvertedRelative_500, infAvertedRelative_750, infAvertedRelative_975, 
                   infAvertedRelative_total_SD, infAvertedRelative_singlemean_SD, infAvertedRelative_distrmean_SEM, immunity, networkIPC))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central",
    ))%>%
  dplyr::select(-name)%>%
  pivot_wider(values_from = value, names_from = location)

dataInfAvertedRelative_3ltcfs_compareCIs$methodCI = factor(dataInfAvertedRelative_3ltcfs_compareCIs$methodCI, levels = selected_measures)

# save(dataInfAvertedRelative_3ltcfs_compareCIs, file = paste0(filepath_outcomes_lot3, "dataInfAvertedRelative_3ltcfs_compareCIs.Rdata"))


######################
### IRRs: ABSOLUTE ###
######################

dataIRR0202_1_1 = f_irr(dataSurveillanceOutput0202_1_1)
dataIRR0202_2_1 = f_irr(dataSurveillanceOutput0202_2_1)
dataIRR0505_2_2 = f_irr(dataSurveillanceOutput0505_2_2)

# 3 LTCFs, selected timings
dataIRR_3ltcfs = rbind(dataIRR0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                       dataIRR0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                       dataIRR0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataIRR_3ltcfs$stratSurveillance = factor(dataIRR_3ltcfs$stratSurveillance, levels = rev(all_strats_3ltcfs), labels = rev(all_strats_3ltcfs_labels))
dataIRR_3ltcfs$targetDailyScreening = factor(dataIRR_3ltcfs$targetDailyScreening, levels = rev(selected_targets), labels = rev(selected_targets_labels))

# prep data for plotting:
dataIRR_3ltcfs_compareCIs = dataIRR_3ltcfs%>%
  mutate(incidenceRate_quantiles_mean = incidenceRateOverallOutbreaks_500,
         incidenceRate_quantiles_lower = incidenceRateOverallOutbreaks_250, 
         incidenceRate_quantiles_upper = incidenceRateOverallOutbreaks_750)%>%
  dplyr::select(-c(incidenceRateOverall_025, incidenceRateOverall_250, incidenceRateOverall_500, incidenceRateOverall_750, incidenceRateOverall_975, 
                   incidenceRateOverallOutbreaks_025, incidenceRateOverallOutbreaks_250, incidenceRateOverallOutbreaks_500, incidenceRateOverallOutbreaks_750, incidenceRateOverallOutbreaks_975, 
                   incidenceRate_total_SD, incidenceRate_singlemean_SD, incidenceRate_distrmean_SEM, immunity, networkIPC,
                   incNosocomial_sum, infAverted_sum, incAfterTesting_sum))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central",
    ))%>%
  dplyr::select(-name)%>%
  pivot_wider(values_from = value, names_from = location)

dataIRR_3ltcfs_compareCIs$methodCI = factor(dataIRR_3ltcfs_compareCIs$methodCI, levels = selected_measures)

# save(dataIRR_3ltcfs_compareCIs, file = paste0(filepath_outcomes_lot3, "dataIRR_3ltcfs_compareCIs.Rdata"))


######################
### IRRs: RELATIVE ###
######################

dataIRRrelative0202_1_1 = f_irr_relative(dataSurveillanceOutput0202_1_1)
dataIRRrelative0202_2_1 = f_irr_relative(dataSurveillanceOutput0202_2_1)
dataIRRrelative0505_2_2 = f_irr_relative(dataSurveillanceOutput0505_2_2)

# 3 LTCFs, selected timings
dataIRRrelative_3ltcfs = rbind(dataIRRrelative0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                       dataIRRrelative0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                       dataIRRrelative0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataIRRrelative_3ltcfs$stratSurveillance = factor(dataIRRrelative_3ltcfs$stratSurveillance, levels = rev(all_strats_3ltcfs), labels = rev(all_strats_3ltcfs_labels))
dataIRRrelative_3ltcfs$targetDailyScreening = factor(dataIRRrelative_3ltcfs$targetDailyScreening, levels = rev(selected_targets), labels = rev(selected_targets_labels))

# prep data for plotting:
dataIRRrelative_3ltcfs_compareCIs = dataIRRrelative_3ltcfs%>%
  mutate(incidenceRate_quantiles_mean = incidenceRateOverallOutbreaks_500,
         incidenceRate_quantiles_lower = incidenceRateOverallOutbreaks_250, 
         incidenceRate_quantiles_upper = incidenceRateOverallOutbreaks_750)%>%
  dplyr::select(-c(incidenceRateOverall_025, incidenceRateOverall_250, incidenceRateOverall_500, incidenceRateOverall_750, incidenceRateOverall_975, 
                   incidenceRateOverallOutbreaks_025, incidenceRateOverallOutbreaks_250, incidenceRateOverallOutbreaks_500, incidenceRateOverallOutbreaks_750, incidenceRateOverallOutbreaks_975, 
                   incidenceRate_total_SD, incidenceRate_singlemean_SD, incidenceRate_distrmean_SEM, immunity, networkIPC,
                   incNosocomialBaseline_sum, incAfterScreening_sum))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central",
    ))%>%
  dplyr::select(-name)%>%
  pivot_wider(values_from = value, names_from = location)

dataIRRrelative_3ltcfs_compareCIs$methodCI = factor(dataIRRrelative_3ltcfs_compareCIs$methodCI, levels = selected_measures)

# save(dataIRRrelative_3ltcfs_compareCIs, file = paste0(filepath_outcomes_lot3, "dataIRRrelative_3ltcfs_compareCIs.Rdata"))


#############################
### PropAverted: Absolute ###
#############################

dataPropAverted0202_1_1 = f_propAverted(dataSurveillanceOutput0202_1_1)
dataPropAverted0202_2_1 = f_propAverted(dataSurveillanceOutput0202_2_1)
dataPropAverted0505_2_2 = f_propAverted(dataSurveillanceOutput0505_2_2)

# 3 LTCFs, selected timings
dataPropAverted_3ltcfs = rbind(dataPropAverted0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                               dataPropAverted0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                               dataPropAverted0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataPropAverted_3ltcfs$stratSurveillance = factor(dataPropAverted_3ltcfs$stratSurveillance, levels = rev(all_strats_3ltcfs), labels = rev(all_strats_3ltcfs_labels))
dataPropAverted_3ltcfs$targetDailyScreening = factor(dataPropAverted_3ltcfs$targetDailyScreening, levels = rev(selected_targets), labels = rev(selected_targets_labels))

# prep data for plotting:
dataPropAverted_3ltcfs_compareCIs = dataPropAverted_3ltcfs%>%
  mutate(propAverted_quantiles_mean = propAvertedOverallOutbreaks_500,
         propAverted_quantiles_lower = propAvertedOverallOutbreaks_250, 
         propAverted_quantiles_upper = propAvertedOverallOutbreaks_750)%>%
  dplyr::select(-c(propAvertedOverall_025, propAvertedOverall_250, propAvertedOverall_500, propAvertedOverall_750, propAvertedOverall_975, 
                   propAvertedOverallOutbreaks_025, propAvertedOverallOutbreaks_250, propAvertedOverallOutbreaks_500, propAvertedOverallOutbreaks_750, propAvertedOverallOutbreaks_975, 
                   propAverted_total_SD, propAverted_singlemean_SD, propAverted_distrmean_SEM, immunity, networkIPC,
                   numOutbreaks, incNosocomial_sum, infAverted_sum))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central",
    ))%>%
  dplyr::select(-name)%>%
  pivot_wider(values_from = value, names_from = location)

dataPropAverted_3ltcfs_compareCIs$methodCI = factor(dataPropAverted_3ltcfs_compareCIs$methodCI, levels = selected_measures)

# save(dataPropAverted_3ltcfs_compareCIs, file = paste0(filepath_outcomes_lot3, "dataPropAverted_3ltcfs_compareCIs.Rdata"))



#############################
### PropAverted: Relative ###
#############################

dataPropAvertedRelative0202_1_1 = f_propAverted_relative(dataSurveillanceOutput0202_1_1)
dataPropAvertedRelative0202_2_1 = f_propAverted_relative(dataSurveillanceOutput0202_2_1)
dataPropAvertedRelative0505_2_2 = f_propAverted_relative(dataSurveillanceOutput0505_2_2)

# 3 LTCFs, selected timings
dataPropAvertedRelative_3ltcfs = rbind(dataPropAvertedRelative0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                               dataPropAvertedRelative0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                               dataPropAvertedRelative0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataPropAvertedRelative_3ltcfs$stratSurveillance = factor(dataPropAvertedRelative_3ltcfs$stratSurveillance, levels = rev(all_strats_3ltcfs), labels = rev(all_strats_3ltcfs_labels))
dataPropAvertedRelative_3ltcfs$targetDailyScreening = factor(dataPropAvertedRelative_3ltcfs$targetDailyScreening, levels = rev(selected_targets), labels = rev(selected_targets_labels))

# prep data for plotting:
dataPropAvertedRelative_3ltcfs_compareCIs = dataPropAvertedRelative_3ltcfs%>%
  mutate(propAverted_quantiles_mean = propAvertedOverallOutbreaks_500,
         propAverted_quantiles_lower = propAvertedOverallOutbreaks_250, 
         propAverted_quantiles_upper = propAvertedOverallOutbreaks_750)%>%
  dplyr::select(-c(propAvertedOverall_025, propAvertedOverall_250, propAvertedOverall_500, propAvertedOverall_750, propAvertedOverall_975, 
                   propAvertedOverallOutbreaks_025, propAvertedOverallOutbreaks_250, propAvertedOverallOutbreaks_500, propAvertedOverallOutbreaks_750, propAvertedOverallOutbreaks_975, 
                   propAverted_total_SD, propAverted_singlemean_SD, propAverted_distrmean_SEM, immunity, networkIPC,
                  incNosocomialAfterBaseline_sum, infAvertedAfterBaseline_sum))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central",
    ))%>%
  dplyr::select(-name)%>%
  pivot_wider(values_from = value, names_from = location)

dataPropAvertedRelative_3ltcfs_compareCIs$methodCI = factor(dataPropAvertedRelative_3ltcfs_compareCIs$methodCI, levels = selected_measures)

# save(dataPropAvertedRelative_3ltcfs_compareCIs, file = paste0(filepath_outcomes_lot3, "dataPropAvertedRelative_3ltcfs_compareCIs.Rdata"))


############################
### TEST POSITIVITY RATE ###
############################

dataTestPositivity0202_1_1 = f_testPositivity(dataSurveillanceOutput0202_1_1)
dataTestPositivity0202_2_1 = f_testPositivity(dataSurveillanceOutput0202_2_1)
dataTestPositivity0505_2_2 = f_testPositivity(dataSurveillanceOutput0505_2_2)

# 3 LTCFs, selected timings
dataTestPositivity_3ltcfs = rbind(dataTestPositivity0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                                       dataTestPositivity0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                                       dataTestPositivity0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataTestPositivity_3ltcfs$stratSurveillance = factor(dataTestPositivity_3ltcfs$stratSurveillance,levels = rev(all_strats_3ltcfs),labels = rev(all_strats_3ltcfs_labels))
dataTestPositivity_3ltcfs$targetDailyScreening = factor(dataTestPositivity_3ltcfs$targetDailyScreening,levels = rev(selected_targets),labels = rev(selected_targets_labels))

# prep data for plotting:
dataTestPositivity_3ltcfs_compareCIs = dataTestPositivity_3ltcfs%>%
  mutate(PCR.positivity_quantiles_mean = PCR.positivity_rate_500,
         PCR.positivity_quantiles_lower = PCR.positivity_rate_250, 
         PCR.positivity_quantiles_upper = PCR.positivity_rate_750,
         RDT.positivity_quantiles_mean = RDT.positivity_rate_500,
         RDT.positivity_quantiles_lower = RDT.positivity_rate_250, 
         RDT.positivity_quantiles_upper = RDT.positivity_rate_750)%>%
  dplyr::select(-c(PCR.positivity_rate_025, PCR.positivity_rate_250, PCR.positivity_rate_500, PCR.positivity_rate_750, PCR.positivity_rate_975,
                   RDT.positivity_rate_025, RDT.positivity_rate_250, RDT.positivity_rate_500, RDT.positivity_rate_750, RDT.positivity_rate_975,
                   PCR.n_test_sum, PCR.n_positive_sum, PCR.positivity_rate_total_SD, PCR.positivity_rate_singlemean_SD, PCR.positivity_rate_distrmean_SEM,
                   RDT.n_test_sum, RDT.n_positive_sum, RDT.positivity_rate_total_SD, RDT.positivity_rate_singlemean_SD, RDT.positivity_rate_distrmean_SEM,
                   networkIPC, immunity))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    Test = case_when(
      grepl("PCR", name) ~ "PCR",
      grepl("RDT", name) ~ "Ag-RDT"),
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central"
    ))%>%
  dplyr::select(-name)%>%
  group_by(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function, Test, methodCI, location)%>%
  dplyr::summarise(value = mean(value))%>%
  pivot_wider(values_from = value, names_from = location)

dataTestPositivity_3ltcfs_compareCIs_routine = filter(dataTestPositivity_3ltcfs_compareCIs, Test == 'PCR', stratSurveillance == 'Baseline (routine PCR)')
dataTestPositivity_3ltcfs_compareCIs_screening = filter(dataTestPositivity_3ltcfs_compareCIs, Test != 'PCR', stratSurveillance != 'Baseline (routine PCR)')

dataTestPositivity_3ltcfs_compareCIs_plottable = rbind(dataTestPositivity_3ltcfs_compareCIs_routine, dataTestPositivity_3ltcfs_compareCIs_screening)
dataTestPositivity_3ltcfs_compareCIs_plottable$methodCI = factor(dataTestPositivity_3ltcfs_compareCIs_plottable$methodCI, levels = selected_measures)

# save(dataTestPositivity_3ltcfs_compareCIs_plottable, file = paste0(filepath_outcomes_lot3, "dataTestPositivity_3ltcfs_compareCIs_plottable.Rdata"))


###################
### SENSITIVITY ###
###################

dataTestSensitivity0202_1_1 = f_sensitivityRealized(dataSurveillanceOutput0202_1_1)
dataTestSensitivity0202_2_1 = f_sensitivityRealized(dataSurveillanceOutput0202_2_1)
dataTestSensitivity0505_2_2 = f_sensitivityRealized(dataSurveillanceOutput0505_2_2)

# 3 LTCFs, selected timings
dataTestSensitivity_3ltcfs = rbind(dataTestSensitivity0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                                   dataTestSensitivity0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                                   dataTestSensitivity0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataTestSensitivity_3ltcfs$stratSurveillance = factor(dataTestSensitivity_3ltcfs$stratSurveillance,levels = rev(all_strats_3ltcfs),labels = rev(all_strats_3ltcfs_labels))
dataTestSensitivity_3ltcfs$targetDailyScreening = factor(dataTestSensitivity_3ltcfs$targetDailyScreening,levels = rev(selected_targets),labels = rev(selected_targets_labels))

# prep data for plotting:
dataTestSensitivity_3ltcfs_compareCIs = dataTestSensitivity_3ltcfs%>%
  mutate(PCR.sensitivity_quantiles_mean = PCR.sensitivity_realized_500,
         PCR.sensitivity_quantiles_lower = PCR.sensitivity_realized_250, 
         PCR.sensitivity_quantiles_upper = PCR.sensitivity_realized_750,
         RDT.sensitivity_quantiles_mean = RDT.sensitivity_realized_500,
         RDT.sensitivity_quantiles_lower = RDT.sensitivity_realized_250, 
         RDT.sensitivity_quantiles_upper = RDT.sensitivity_realized_750)%>%
  dplyr::select(-c(PCR.sensitivity_realized_025, PCR.sensitivity_realized_250, PCR.sensitivity_realized_500, PCR.sensitivity_realized_750, PCR.sensitivity_realized_975,
                   RDT.sensitivity_realized_025, RDT.sensitivity_realized_250, RDT.sensitivity_realized_500, RDT.sensitivity_realized_750, RDT.sensitivity_realized_975,
                   PCR.n_test_true_positive_sum, PCR.n_positive_and_tested_sum, PCR.sensitivity_total_SD, PCR.sensitivity_singlemean_SD, PCR.sensitivity_distrmean_SEM,
                   RDT.n_test_true_positive_sum, RDT.n_positive_and_tested_sum, RDT.sensitivity_total_SD, RDT.sensitivity_singlemean_SD, RDT.sensitivity_distrmean_SEM,
                   networkIPC, immunity))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    Test = case_when(
      grepl("PCR", name) ~ "PCR",
      grepl("RDT", name) ~ "Ag-RDT"),
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central"
    ))%>%
  dplyr::select(-name)%>%
  group_by(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function, Test, methodCI, location)%>%
  dplyr::summarise(value = mean(value))%>%
  pivot_wider(values_from = value, names_from = location)

dataTestSensitivity_3ltcfs_compareCIs_routine = filter(dataTestSensitivity_3ltcfs_compareCIs, Test == 'PCR', stratSurveillance == 'Baseline (routine PCR)')
dataTestSensitivity_3ltcfs_compareCIs_screening = filter(dataTestSensitivity_3ltcfs_compareCIs, Test != 'PCR', stratSurveillance != 'Baseline (routine PCR)')

dataTestSensitivity_3ltcfs_compareCIs_plottable = rbind(dataTestSensitivity_3ltcfs_compareCIs_routine, dataTestSensitivity_3ltcfs_compareCIs_screening)
dataTestSensitivity_3ltcfs_compareCIs_plottable$methodCI = factor(dataTestSensitivity_3ltcfs_compareCIs_plottable$methodCI, levels = selected_measures)

# save(dataTestSensitivity_3ltcfs_compareCIs_plottable, file = paste0(filepath_outcomes_lot3, "dataTestSensitivity_3ltcfs_compareCIs_plottable.Rdata"))


###################
### SPECIFICITY ###
###################

dataTestSpecificity0202_1_1 = f_specificityRealized(dataSurveillanceOutput0202_1_1)
dataTestSpecificity0202_2_1 = f_specificityRealized(dataSurveillanceOutput0202_2_1)
dataTestSpecificity0505_2_2 = f_specificityRealized(dataSurveillanceOutput0505_2_2)

# 3 LTCFs, selected timings
dataTestSpecificity_3ltcfs = rbind(dataTestSpecificity0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                                   dataTestSpecificity0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                                   dataTestSpecificity0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataTestSpecificity_3ltcfs$stratSurveillance = factor(dataTestSpecificity_3ltcfs$stratSurveillance,levels = rev(all_strats_3ltcfs),labels = rev(all_strats_3ltcfs_labels))
dataTestSpecificity_3ltcfs$targetDailyScreening = factor(dataTestSpecificity_3ltcfs$targetDailyScreening,levels = rev(selected_targets),labels = rev(selected_targets_labels))

# prep data for plotting:
dataTestSpecificity_3ltcfs_compareCIs = dataTestSpecificity_3ltcfs%>%
  mutate(PCR.specificity_quantiles_mean = PCR.specificity_realized_500,
         PCR.specificity_quantiles_lower = PCR.specificity_realized_250, 
         PCR.specificity_quantiles_upper = PCR.specificity_realized_750,
         RDT.specificity_quantiles_mean = RDT.specificity_realized_500,
         RDT.specificity_quantiles_lower = RDT.specificity_realized_250, 
         RDT.specificity_quantiles_upper = RDT.specificity_realized_750)%>%
  dplyr::select(-c(PCR.specificity_realized_025, PCR.specificity_realized_250, PCR.specificity_realized_500, PCR.specificity_realized_750, PCR.specificity_realized_975,
                   RDT.specificity_realized_025, RDT.specificity_realized_250, RDT.specificity_realized_500, RDT.specificity_realized_750, RDT.specificity_realized_975,
                   PCR.n_test_true_negative_sum, PCR.n_negative_and_tested_sum, PCR.specificity_total_SD, PCR.specificity_singlemean_SD, PCR.specificity_distrmean_SEM,
                   RDT.n_test_true_negative_sum, RDT.n_negative_and_tested_sum, RDT.specificity_total_SD, RDT.specificity_singlemean_SD, RDT.specificity_distrmean_SEM,
                   networkIPC, immunity))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    Test = case_when(
      grepl("PCR", name) ~ "PCR",
      grepl("RDT", name) ~ "Ag-RDT"),
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central"
    ))%>%
  dplyr::select(-name)%>%
  group_by(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function, Test, methodCI, location)%>%
  dplyr::summarise(value = mean(value))%>%
  pivot_wider(values_from = value, names_from = location)

dataTestSpecificity_3ltcfs_compareCIs_routine = filter(dataTestSpecificity_3ltcfs_compareCIs, Test == 'PCR', stratSurveillance == 'Baseline (routine PCR)')
dataTestSpecificity_3ltcfs_compareCIs_screening = filter(dataTestSpecificity_3ltcfs_compareCIs, Test != 'PCR', stratSurveillance != 'Baseline (routine PCR)')

dataTestSpecificity_3ltcfs_compareCIs_plottable = rbind(dataTestSpecificity_3ltcfs_compareCIs_routine, dataTestSpecificity_3ltcfs_compareCIs_screening)
dataTestSpecificity_3ltcfs_compareCIs_plottable$methodCI = factor(dataTestSpecificity_3ltcfs_compareCIs_plottable$methodCI, levels = selected_measures)

# save(dataTestSpecificity_3ltcfs_compareCIs_plottable, file = paste0(filepath_outcomes_lot3, "dataTestSpecificity_3ltcfs_compareCIs_plottable.Rdata"))



###########
### PPV ### Positive predictive value
###########

dataTestPPV0202_1_1 = f_PPV(dataSurveillanceOutput0202_1_1)
dataTestPPV0202_2_1 = f_PPV(dataSurveillanceOutput0202_2_1)
dataTestPPV0505_2_2 = f_PPV(dataSurveillanceOutput0505_2_2)

# 3 LTCFs, selected timings
dataTestPPV_3ltcfs = rbind(dataTestPPV0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                           dataTestPPV0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                           dataTestPPV0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataTestPPV_3ltcfs$stratSurveillance = factor(dataTestPPV_3ltcfs$stratSurveillance,levels = rev(all_strats_3ltcfs),labels = rev(all_strats_3ltcfs_labels))
dataTestPPV_3ltcfs$targetDailyScreening = factor(dataTestPPV_3ltcfs$targetDailyScreening,levels = rev(selected_targets),labels = rev(selected_targets_labels))

# prep data for plotting:
dataTestPPV_3ltcfs_compareCIs = dataTestPPV_3ltcfs%>%
  mutate(PCR.PPV_quantiles_mean = PCR.PPV_500,
         PCR.PPV_quantiles_lower = PCR.PPV_250, 
         PCR.PPV_quantiles_upper = PCR.PPV_750,
         RDT.PPV_quantiles_mean = RDT.PPV_500,
         RDT.PPV_quantiles_lower = RDT.PPV_250, 
         RDT.PPV_quantiles_upper = RDT.PPV_750)%>%
  dplyr::select(-c(PCR.PPV_025, PCR.PPV_250, PCR.PPV_500, PCR.PPV_750, PCR.PPV_975,
                   RDT.PPV_025, RDT.PPV_250, RDT.PPV_500, RDT.PPV_750, RDT.PPV_975,
                   PCR.n_test_true_positive_sum, PCR.n_test_positive_sum, PCR.PPV_total_SD, PCR.PPV_singlemean_SD, PCR.PPV_distrmean_SEM,
                   RDT.n_test_true_positive_sum, RDT.n_test_positive_sum, RDT.PPV_total_SD, RDT.PPV_singlemean_SD, RDT.PPV_distrmean_SEM,
                   networkIPC, immunity))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    Test = case_when(
      grepl("PCR", name) ~ "PCR",
      grepl("RDT", name) ~ "Ag-RDT"),
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central"
    ))%>%
  dplyr::select(-name)%>%
  group_by(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function, Test, methodCI, location)%>%
  dplyr::summarise(value = mean(value))%>%
  pivot_wider(values_from = value, names_from = location)

dataTestPPV_3ltcfs_compareCIs_routine = filter(dataTestPPV_3ltcfs_compareCIs, Test == 'PCR', stratSurveillance == 'Baseline (routine PCR)')
dataTestPPV_3ltcfs_compareCIs_screening = filter(dataTestPPV_3ltcfs_compareCIs, Test != 'PCR', stratSurveillance != 'Baseline (routine PCR)')

dataTestPPV_3ltcfs_compareCIs_plottable = rbind(dataTestPPV_3ltcfs_compareCIs_routine, dataTestPPV_3ltcfs_compareCIs_screening)
dataTestPPV_3ltcfs_compareCIs_plottable$methodCI = factor(dataTestPPV_3ltcfs_compareCIs_plottable$methodCI, levels = selected_measures)

# save(dataTestPPV_3ltcfs_compareCIs_plottable, file = paste0(filepath_outcomes_lot3, "dataTestPPV_3ltcfs_compareCIs_plottable.Rdata"))


###########
### NPV ### Negative predictive value
###########

dataTestNPV0202_1_1 = f_NPV(dataSurveillanceOutput0202_1_1)
dataTestNPV0202_2_1 = f_NPV(dataSurveillanceOutput0202_2_1)
dataTestNPV0505_2_2 = f_NPV(dataSurveillanceOutput0505_2_2)

# 3 LTCFs, selected timings
dataTestNPV_3ltcfs = rbind(dataTestNPV0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                           dataTestNPV0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                           dataTestNPV0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataTestNPV_3ltcfs$stratSurveillance = factor(dataTestNPV_3ltcfs$stratSurveillance,levels = rev(all_strats_3ltcfs),labels = rev(all_strats_3ltcfs_labels))
dataTestNPV_3ltcfs$targetDailyScreening = factor(dataTestNPV_3ltcfs$targetDailyScreening,levels = rev(selected_targets),labels = rev(selected_targets_labels))

# prep data for plotting:
dataTestNPV_3ltcfs_compareCIs = dataTestNPV_3ltcfs%>%
  mutate(PCR.NPV_quantiles_mean = PCR.NPV_500,
         PCR.NPV_quantiles_lower = PCR.NPV_250, 
         PCR.NPV_quantiles_upper = PCR.NPV_750,
         RDT.NPV_quantiles_mean = RDT.NPV_500,
         RDT.NPV_quantiles_lower = RDT.NPV_250, 
         RDT.NPV_quantiles_upper = RDT.NPV_750)%>%
  dplyr::select(-c(PCR.NPV_025, PCR.NPV_250, PCR.NPV_500, PCR.NPV_750, PCR.NPV_975,
                   RDT.NPV_025, RDT.NPV_250, RDT.NPV_500, RDT.NPV_750, RDT.NPV_975,
                   PCR.n_test_true_negative_sum, PCR.n_test_negative_sum, PCR.NPV_total_SD, PCR.NPV_singlemean_SD, PCR.NPV_distrmean_SEM,
                   RDT.n_test_true_negative_sum, RDT.n_test_negative_sum, RDT.NPV_total_SD, RDT.NPV_singlemean_SD, RDT.NPV_distrmean_SEM,
                   networkIPC, immunity))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    Test = case_when(
      grepl("PCR", name) ~ "PCR",
      grepl("RDT", name) ~ "Ag-RDT"),
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central"
    ))%>%
  dplyr::select(-name)%>%
  group_by(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function, Test, methodCI, location)%>%
  dplyr::summarise(value = mean(value))%>%
  pivot_wider(values_from = value, names_from = location)

dataTestNPV_3ltcfs_compareCIs_routine = filter(dataTestNPV_3ltcfs_compareCIs, Test == 'PCR', stratSurveillance == 'Baseline (routine PCR)')
dataTestNPV_3ltcfs_compareCIs_screening = filter(dataTestNPV_3ltcfs_compareCIs, Test != 'PCR', stratSurveillance != 'Baseline (routine PCR)')

dataTestNPV_3ltcfs_compareCIs_plottable = rbind(dataTestNPV_3ltcfs_compareCIs_routine, dataTestNPV_3ltcfs_compareCIs_screening)
dataTestNPV_3ltcfs_compareCIs_plottable$methodCI = factor(dataTestNPV_3ltcfs_compareCIs_plottable$methodCI, levels = selected_measures)

# save(dataTestNPV_3ltcfs_compareCIs_plottable, file = paste0(filepath_outcomes_lot3, "dataTestNPV_3ltcfs_compareCIs_plottable.Rdata"))


###############################
### CASES DETECTED PER TEST ###
###############################

dataCasesDetectedPerTest0202_1_1 = f_casesDetectedPerTest(dataSurveillanceOutput0202_1_1)
dataCasesDetectedPerTest0202_2_1 = f_casesDetectedPerTest(dataSurveillanceOutput0202_2_1)
dataCasesDetectedPerTest0505_2_2 = f_casesDetectedPerTest(dataSurveillanceOutput0505_2_2)

# 3 LTCFs, selected timings
dataCasesDetectedPerTest_3ltcfs = rbind(dataCasesDetectedPerTest0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                                        dataCasesDetectedPerTest0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                                        dataCasesDetectedPerTest0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataCasesDetectedPerTest_3ltcfs$stratSurveillance = factor(dataCasesDetectedPerTest_3ltcfs$stratSurveillance,levels = rev(all_strats_3ltcfs),labels = rev(all_strats_3ltcfs_labels))
dataCasesDetectedPerTest_3ltcfs$targetDailyScreening = factor(dataCasesDetectedPerTest_3ltcfs$targetDailyScreening,levels = rev(selected_targets),labels = rev(selected_targets_labels))

# prep data for plotting:
dataCasesDetectedPerTest_3ltcfs_compareCIs = dataCasesDetectedPerTest_3ltcfs%>%
  mutate(PCR.detections_per_test_quantiles_mean = PCR.detections_per_test_500,
         PCR.detections_per_test_quantiles_lower = PCR.detections_per_test_250, 
         PCR.detections_per_test_quantiles_upper = PCR.detections_per_test_750,
         RDT.detections_per_test_quantiles_mean = RDT.detections_per_test_500,
         RDT.detections_per_test_quantiles_lower = RDT.detections_per_test_250, 
         RDT.detections_per_test_quantiles_upper = RDT.detections_per_test_750)%>%
  dplyr::select(-c(PCR.detections_per_test_025, PCR.detections_per_test_250, PCR.detections_per_test_500, PCR.detections_per_test_750, PCR.detections_per_test_975,
                   RDT.detections_per_test_025, RDT.detections_per_test_250, RDT.detections_per_test_500, RDT.detections_per_test_750, RDT.detections_per_test_975,
                   PCR.n_test_sum, PCR.n_test_true_positive_sum, PCR.detections_per_test_total_SD, PCR.detections_per_test_singlemean_SD, PCR.detections_per_test_distrmean_SEM,
                   RDT.n_test_sum, RDT.n_test_true_positive_sum, RDT.detections_per_test_total_SD, RDT.detections_per_test_singlemean_SD, RDT.detections_per_test_distrmean_SEM,
                   networkIPC, immunity))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    Test = case_when(
      grepl("PCR", name) ~ "PCR",
      grepl("RDT", name) ~ "Ag-RDT"),
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central"
    ))%>%
  dplyr::select(-name)%>%
  group_by(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function, Test, methodCI, location)%>%
  dplyr::summarise(value = mean(value))%>%
  pivot_wider(values_from = value, names_from = location)

dataCasesDetectedPerTest_3ltcfs_compareCIs_routine = filter(dataCasesDetectedPerTest_3ltcfs_compareCIs, Test == 'PCR', stratSurveillance == 'Baseline (routine PCR)')
dataCasesDetectedPerTest_3ltcfs_compareCIs_screening = filter(dataCasesDetectedPerTest_3ltcfs_compareCIs, Test != 'PCR', stratSurveillance != 'Baseline (routine PCR)')

dataCasesDetectedPerTest_3ltcfs_compareCIs_plottable = rbind(dataCasesDetectedPerTest_3ltcfs_compareCIs_routine, dataCasesDetectedPerTest_3ltcfs_compareCIs_screening)
dataCasesDetectedPerTest_3ltcfs_compareCIs_plottable$methodCI = factor(dataCasesDetectedPerTest_3ltcfs_compareCIs_plottable$methodCI, levels = selected_measures)

# save(dataCasesDetectedPerTest_3ltcfs_compareCIs_plottable, file = paste0(filepath_outcomes_lot3, "dataCasesDetectedPerTest_3ltcfs_compareCIs_plottable.Rdata"))


###############################
### CASES AVERTED PER TEST ###
###############################

dataCasesAvertedPerTest0202_1_1 = f_casesAvertedPerTest(dataSurveillanceOutput0202_1_1)
dataCasesAvertedPerTest0202_2_1 = f_casesAvertedPerTest(dataSurveillanceOutput0202_2_1)
dataCasesAvertedPerTest0505_2_2 = f_casesAvertedPerTest(dataSurveillanceOutput0505_2_2)

# 3 LTCFs, selected timings
dataCasesAvertedPerTest_3ltcfs = rbind(dataCasesAvertedPerTest0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels[1]), 
                                       dataCasesAvertedPerTest0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels[2]), 
                                       dataCasesAvertedPerTest0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels[3]))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym') & targetDailyScreening %in% c('Patients', 'Staff')))%>%
  filter(!(stratSurveillance %in% c('adm', 'sym', 'adm_sym')  & typeDailyScreening %in% c('RDT1', 'RDT2')))%>%
  mutate(networkIPC = "network1_ipc1",
         immunity = "20% immunized",
         targetDailyScreening = ifelse(stratSurveillance %in% c('adm', 'sym', 'adm_sym'), 'None', targetDailyScreening))%>%
  filter(stratSurveillance %in% all_strats_3ltcfs)%>%
  distinct()

dataCasesAvertedPerTest_3ltcfs$stratSurveillance = factor(dataCasesAvertedPerTest_3ltcfs$stratSurveillance,levels = rev(all_strats_3ltcfs),labels = rev(all_strats_3ltcfs_labels))
dataCasesAvertedPerTest_3ltcfs$targetDailyScreening = factor(dataCasesAvertedPerTest_3ltcfs$targetDailyScreening,levels = rev(selected_targets),labels = rev(selected_targets_labels))

# prep data for plotting:
dataCasesAvertedPerTest_3ltcfs_compareCIs = dataCasesAvertedPerTest_3ltcfs%>%
  mutate(PCR.averted_per_test_quantiles_mean = PCR.averted_per_test_500,
         PCR.averted_per_test_quantiles_lower = PCR.averted_per_test_250, 
         PCR.averted_per_test_quantiles_upper = PCR.averted_per_test_750,
         RDT.averted_per_test_quantiles_mean = RDT.averted_per_test_500,
         RDT.averted_per_test_quantiles_lower = RDT.averted_per_test_250, 
         RDT.averted_per_test_quantiles_upper = RDT.averted_per_test_750)%>%
  dplyr::select(-c(PCR.averted_per_test_025, PCR.averted_per_test_250, PCR.averted_per_test_500, PCR.averted_per_test_750, PCR.averted_per_test_975,
                   RDT.averted_per_test_025, RDT.averted_per_test_250, RDT.averted_per_test_500, RDT.averted_per_test_750, RDT.averted_per_test_975,
                   PCR.n_test_sum, PCR.n_infAverted_sum, PCR.averted_per_test_total_SD, PCR.averted_per_test_singlemean_SD, PCR.averted_per_test_distrmean_SEM,
                   RDT.n_test_sum, RDT.n_infAverted_sum, RDT.averted_per_test_total_SD, RDT.averted_per_test_singlemean_SD, RDT.averted_per_test_distrmean_SEM,
                   networkIPC, immunity))%>%
  pivot_longer(-c(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function))%>%
  mutate(
    Test = case_when(
      grepl("PCR", name) ~ "PCR",
      grepl("RDT", name) ~ "Ag-RDT"),
    methodCI = case_when(
      grepl("quantile", name) ~ "quantile",
      grepl("total", name) ~ "total",
      grepl("singlemean", name) ~ "single mean",
      grepl("distrmean", name) ~ "distribution of means",
      grepl("bootstrap", name) ~ "bootstrap"),
    location = case_when(
      grepl("_upper", name) ~ "upper",
      grepl("_lower", name) ~ "lower",
      TRUE ~ "central"
    ))%>%
  dplyr::select(-name)%>%
  group_by(stratSurveillance, typeDailyScreening, targetDailyScreening, LTCF, sensitivity_function, Test, methodCI, location)%>%
  dplyr::summarise(value = mean(value))%>%
  pivot_wider(values_from = value, names_from = location)

dataCasesAvertedPerTest_3ltcfs_compareCIs_routine = filter(dataCasesAvertedPerTest_3ltcfs_compareCIs, Test == 'PCR', stratSurveillance == 'Baseline (routine PCR)')
dataCasesAvertedPerTest_3ltcfs_compareCIs_screening = filter(dataCasesAvertedPerTest_3ltcfs_compareCIs, Test != 'PCR', stratSurveillance != 'Baseline (routine PCR)')

dataCasesAvertedPerTest_3ltcfs_compareCIs_plottable = rbind(dataCasesAvertedPerTest_3ltcfs_compareCIs_routine, dataCasesAvertedPerTest_3ltcfs_compareCIs_screening)
dataCasesAvertedPerTest_3ltcfs_compareCIs_plottable$methodCI = factor(dataCasesAvertedPerTest_3ltcfs_compareCIs_plottable$methodCI, levels = selected_measures)

# save(dataCasesAvertedPerTest_3ltcfs_compareCIs_plottable, file = paste0(filepath_outcomes_lot3, "dataCasesAvertedPerTest_3ltcfs_compareCIs_plottable.Rdata"))



#############################
### COST PER CASE AVERTED ###
#############################

strats_costPerCaseAverted = c("adm_sym", "d01", "adm_sym_d01", "adm_sym_d01_d05")

econData0202_1_1 = dataSurveillanceOutput0202_1_1%>%
  filter(stratSurveillance %in% strats_costPerCaseAverted,
         sensitivity_function == "time-varying", targetDailyScreening == c("All"), typeDailyScreening == "RDT2")
econData0202_2_1 = dataSurveillanceOutput0202_2_1%>%
  filter(stratSurveillance %in% strats_costPerCaseAverted,
         sensitivity_function == "time-varying", targetDailyScreening == c("All"), typeDailyScreening == "RDT2")
econData0505_2_2 = dataSurveillanceOutput0505_2_2%>%
  filter(stratSurveillance %in% strats_costPerCaseAverted,
         sensitivity_function == "time-varying", targetDailyScreening == c("All"), typeDailyScreening == "RDT2")

### LOOPS 1

# initialize loops
vec_costs_pcr = c(5, 10, 25, 50, 100)
vec_costs_rdt = c(1, 2, 5, 10, 20)

dataCostPerCaseAverted0202_1_1 = data.frame()
dataCostPerCaseAverted0202_2_1 = data.frame()
dataCostPerCaseAverted0505_2_2 = data.frame()

### LOOP 1 0202_1_1
for(cost_pcr_t in vec_costs_pcr){
  print(cost_pcr_t)
  for(cost_rdt_t in vec_costs_rdt){
    dataCostPerCaseAverted0202_1_1_temp = f_costPerCaseAverted(econData0202_1_1, cost_rdt_t, cost_pcr_t)
    dataCostPerCaseAverted0202_1_1 = rbind(dataCostPerCaseAverted0202_1_1, data.frame(dataCostPerCaseAverted0202_1_1_temp))
  }
}

### LOOP 2 0202_2_1
for(cost_pcr_t in vec_costs_pcr){
  print(cost_pcr_t)
  for(cost_rdt_t in vec_costs_rdt){
    dataCostPerCaseAverted0202_2_1_temp = f_costPerCaseAverted(econData0202_2_1, cost_rdt_t, cost_pcr_t)
    dataCostPerCaseAverted0202_2_1 = rbind(dataCostPerCaseAverted0202_2_1, data.frame(dataCostPerCaseAverted0202_2_1_temp))
  }
}

### LOOP 3 0505_2_2
for(cost_pcr_t in vec_costs_pcr){
  print(cost_pcr_t)
  for(cost_rdt_t in vec_costs_rdt){
    dataCostPerCaseAverted0505_2_2_temp = f_costPerCaseAverted(econData0505_2_2, cost_rdt_t, cost_pcr_t)
    dataCostPerCaseAverted0505_2_2 = rbind(dataCostPerCaseAverted0505_2_2, data.frame(dataCostPerCaseAverted0505_2_2_temp))
  }
}


dataCostPerCaseAverted_plottable = rbind(dataCostPerCaseAverted0202_1_1%>%mutate(LTCF = vec_3ltcfs_labels_control[1]),
                                         dataCostPerCaseAverted0202_2_1%>%mutate(LTCF = vec_3ltcfs_labels_control[2]),
                                         dataCostPerCaseAverted0505_2_2%>%mutate(LTCF = vec_3ltcfs_labels_control[3]))

dataCostPerCaseAverted_plottable$stratSurveillance = factor(dataCostPerCaseAverted_plottable$stratSurveillance,
                                                            levels = strats_costPerCaseAverted,
                                                            labels = c("routine RT-PCR testing", "1-round Ag-RDT screening",
                                                                       "routine RT-PCR testing + 1-round Ag-RDT screening", "routine RT-PCR testing + 2-round Ag-RDT screening"))

# save(dataCostPerCaseAverted_plottable, file = paste0(filepath_outcomes_lot3, "dataCostsPerCaseAverted_3ltcfs_plottable.Rdata"))
